workflows:
  ios_release:
    name: iOS Release Build
    platform: ios
    flutter: stable
    xcode: latest
    ios:
      export_method: app-store  # Si tu veux une version App Store, sinon utilise 'ad-hoc' ou 'development'
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign  # Build pour release sans signature
    artifacts:
      - *.ipa  # C'est ici que le fichier .ipa sera généré
