workflows:
  ios_release:
    name: iOS Release Build
    platform: ios
    flutter: stable
    xcode: latest
    ios:
      export_method: app-store  # App Store ou Ad-Hoc ou Development selon ton cas
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa  # Assure-toi que c'est le bon chemin pour ton .ipa
