workflows:
  # Workflow pour la construction et la distribution
  release:
    name: Release Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    platforms:
      ios:
        build:
          # Arguments de la construction pour iOS
          build_mode: release
          flutter_build_args: 
            - --flavor ios-production
            - -t lib/main_prod.dart
    steps:
      # Étapes de construction
      - checkout
      - flutter/packages-get
      - flutter/flutter-build:
          ios: true
          android: false
          web: false
          macos: false
          linux: false
          windows: false
      - upload-artifact:
          name: ipa
          path: build/ios/ipa/*.ipa

