name: firstprojet
description: "A new Flutter project."

publish_to: 'none' # Ne pas publier sur pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  intl: ^0.18.0 # Mise à jour vers la dernière version stable compatible
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.0
  pdf: ^3.7.2
  printing: ^5.9.0
  shimmer: ^3.0.0  # Effet Shimmer
  syncfusion_flutter_charts: ^28.2.4+1  # Graphiques Syncfusion
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
