name: Build iOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build iOS app
    runs-on: macos-latest  # Utilisez un runner macOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Vérifie le code de votre dépôt

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # Version stable de Flutter

      - name: Install dependencies
        run: flutter pub get  # Installe les dépendances Flutter

      - name: Build iOS
        run: flutter build ios --release --no-codesign  # Construire l'app en mode release sans signature

      - name: Archive iOS app
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner archive -archivePath build/ios/Runner.xcarchive
          xcodebuild -exportArchive -archivePath build/ios/Runner.xcarchive -exportPath build/ios/Runner.ipa -exportOptionsPlist exportOptions.plist

      - name: Upload .ipa as artifact
        uses: actions/upload-artifact@v2  # Upload artifact avec la version v2
        with:
          name: ios-app
          path: Runner.ipa  # Chemin vers le fichier .ipa généré
