name: Build iOS App

on:
  push:
    branches:
      - main  # Exécuter lorsque vous poussez sur la branche principale
  pull_request:
    branches:
      - main  # Exécuter pour les pull requests sur la branche principale

jobs:
  build:
    name: Build iOS app
    runs-on: macos-latest  # Utilise une machine macOS pour les builds iOS
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Vérifie le code de votre dépôt
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # Utiliser la version stable de Flutter
        
      - name: Install dependencies
        run: flutter pub get  # Installe les dépendances Flutter

      - name: Build iOS
        run: flutter build ios --release --no-codesign  # Construire l'app en mode release sans signature

      - name: Export .ipa file
        run: |
          cd build/ios/iphoneos
          xcodebuild -exportArchive \
            -archivePath Runner.xcarchive \
            -exportPath ./Runner.ipa \
            -exportOptionsPlist exportOptions.plist  # Utilisez votre propre exportOptions.plist

      - name: Upload .ipa as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: build/ios/iphoneos/Runner.ipa  # Chemin vers le fichier .ipa
